# Generated by Django 5.0.4 on 2024-04-16 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_height_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(default=160, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
