# Generated by Django 5.0.4 on 2024-04-16 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(default=160, error_messages={'max_value': 'Height cannot exceed 300.', 'min_value': 'Height must be at least 50.'}, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(default=60, error_messages={'max_value': 'Weight cannot exceed 600.', 'min_value': 'Weight must be at least 20.'}, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
