# Generated by Django 5.0.4 on 2024-04-16 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.PositiveIntegerField(default=2000, error_messages={'max_value': 'you must be at least 5 years old.', 'min_value': 'Year of birth must be at least 1900.'}, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
