# Generated by Django 5.0.4 on 2024-04-17 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_year_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('dificulty_level', models.PositiveIntegerField(default=1, error_messages={'max_value': 'Dificulty level cannot exceed 3.', 'min_value': 'Dificulty level must be at least 1.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
