# Generated by Django 5.0.4 on 2024-04-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exercise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='StrengthExercise',
        ),
    ]
