# Generated by Django 5.0.4 on 2024-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_exercise_strengthexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(related_name='primary_affected_muscles', to='core.musclegroup'),
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(related_name='secondary_affected_muscles', to='core.musclegroup'),
        ),
    ]
