# Generated by Django 5.0.4 on 2024-04-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_strengthexercise_primary_muscle_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclegroup',
            name='description',
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('abs', 'Abs'), ('glutes', 'Glutes'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves')], max_length=255, unique=True),
        ),
    ]
