# Generated by Django 5.0.4 on 2024-04-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_musclegroup_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthexercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(related_name='strength_primary_muscle_groups', to='core.musclegroup'),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(related_name='strength_secondary_muscle_groups', to='core.musclegroup'),
        ),
        migrations.CreateModel(
            name='TrackExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('run', 'Running'), ('walk', 'Walking'), ('jog', 'Jogging')], max_length=255, unique=True)),
                ('primary_muscle_groups', models.ManyToManyField(related_name='track_primary_muscle_groups', to='core.musclegroup')),
                ('secondary_muscle_groups', models.ManyToManyField(related_name='track_secondary_muscle_groups', to='core.musclegroup')),
            ],
        ),
    ]
