# Generated by Django 5.0.4 on 2024-04-27 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_strengthexercise_primary_muscle_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_started', models.TimeField()),
                ('time_ended', models.TimeField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField(default=10, error_messages={'max_value': 'Reps cannot exceed 50.', 'min_value': 'Reps must be at least 1.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('sets', models.PositiveIntegerField(default=1, error_messages={'max_value': 'Reps cannot exceed 50.', 'min_value': 'Reps must be at least 1.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strengthexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
