# Generated by Django 5.0.9 on 2024-10-02 09:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_strengthexerciselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strengthexerciselog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='strengthexerciselog',
            name='time_ended',
        ),
        migrations.RemoveField(
            model_name='strengthexerciselog',
            name='time_started',
        ),
        migrations.AddField(
            model_name='strengthexerciselog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TrackExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories_burned', models.PositiveIntegerField()),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, error_messages={'min_value': 'Distance must be at least 0.0.'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pace', models.DurationField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trackexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
