# Generated by Django 5.0.9 on 2024-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_trackexercise_primary_muscle_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackexercise',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='trackexercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(related_name='primary_%(class)s_set', to='core.musclegroup'),
        ),
        migrations.AddField(
            model_name='trackexercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(related_name='secondary_%(class)s_set', to='core.musclegroup'),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(related_name='primary_%(class)s_set', to='core.musclegroup'),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(related_name='secondary_%(class)s_set', to='core.musclegroup'),
        ),
    ]
