# Generated by Django 5.0.9 on 2024-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_trackexercise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackexercise',
            name='description',
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(related_name='strength_primary_muscle_groups', to='core.musclegroup'),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(related_name='strength_secondary_muscle_groups', to='core.musclegroup'),
        ),
        migrations.AlterField(
            model_name='trackexercise',
            name='primary_muscle_groups',
            field=models.ManyToManyField(related_name='track_primary_muscle_groups', to='core.musclegroup'),
        ),
        migrations.AlterField(
            model_name='trackexercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(related_name='track_secondary_muscle_groups', to='core.musclegroup'),
        ),
    ]
