# Generated by Django 5.0.9 on 2024-11-04 07:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_trackexercise_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthexercise',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.strengthExercise_image_file_path),
        ),
    ]
